//! Minimal ADIF (Amateur Data Interchange Format) export of the QSO log —
//! just enough tags (CALL/QSO_DATE/TIME_ON/MODE) for other loggers to import
//! real connected-mode contacts. BAND/FREQ are omitted since this app never
//! tracks frequency anywhere.

use pr_core::QsoLogEntry;

pub fn format_adif(log: &[QsoLogEntry]) -> String {
    let mut out = String::from("Generated by Packet Radio Client\n<EOH>\n");
    for entry in log {
        let call = entry.callsign.trim();
        let (date, time) = split_started(&entry.started);
        out.push_str(&format!(
            "<CALL:{}>{call} <QSO_DATE:{}>{date} <TIME_ON:{}>{time} <MODE:6>PACKET <EOR>\n",
            call.len(),
            date.len(),
            time.len(),
        ));
    }
    out
}

/// "YYYY-MM-DD HH:MM:SS" -> ("YYYYMMDD", "HHMM"), ADIF's date/time formats.
fn split_started(started: &str) -> (String, String) {
    let date = started.get(0..10).unwrap_or("").replace('-', "");
    let time = started.get(11..16).unwrap_or("").replace(':', "");
    (date, time)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn formats_one_record() {
        let log = vec![QsoLogEntry {
            callsign: "KD3BFP-9".to_string(),
            port_id: "port-1".to_string(),
            started: "2026-07-27 20:45:39".to_string(),
            ended: Some("2026-07-27 20:50:00".to_string()),
        }];
        let adif = format_adif(&log);
        assert!(adif.contains("<CALL:8>KD3BFP-9"));
        assert!(adif.contains("<QSO_DATE:8>20260727"));
        assert!(adif.contains("<TIME_ON:4>2045"));
        assert!(adif.contains("<MODE:6>PACKET"));
        assert!(adif.contains("<EOR>"));
    }
}
