//! Minimal ADIF (Amateur Data Interchange Format) export of CQ contacts
//! logged via the mailbox's CQ command. BAND/FREQ are omitted since this app
//! never tracks frequency.

use pr_core::QsoLogEntry;

/// Format only `from_cq = true` entries as ADIF, including QTH when present.
pub fn format_adif(log: &[QsoLogEntry]) -> String {
    let mut out = String::from("Generated by Packet Radio Client\n<EOH>\n");
    for entry in log.iter().filter(|e| e.from_cq) {
        let call = entry.callsign.trim();
        let (date, time) = split_started(&entry.started);
        let mut record = format!(
            "<CALL:{}>{call} <QSO_DATE:{}>{date} <TIME_ON:{}>{time} <MODE:6>PACKET",
            call.len(),
            date.len(),
            time.len(),
        );
        if let Some(qth) = entry.location.as_deref().filter(|s| !s.is_empty()) {
            record.push_str(&format!(" <QTH:{}>{qth}", qth.len()));
        }
        record.push_str(" <EOR>\n");
        out.push_str(&record);
    }
    out
}

/// "YYYY-MM-DD HH:MM:SS" -> ("YYYYMMDD", "HHMM"), ADIF's date/time formats.
fn split_started(started: &str) -> (String, String) {
    let date = started.get(0..10).unwrap_or("").replace('-', "");
    let time = started.get(11..16).unwrap_or("").replace(':', "");
    (date, time)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cq_entry(callsign: &str, started: &str, location: Option<&str>) -> QsoLogEntry {
        QsoLogEntry {
            callsign: callsign.to_string(),
            port_id: "port-1".to_string(),
            started: started.to_string(),
            ended: None,
            location: location.map(str::to_string),
            from_cq: true,
        }
    }

    #[test]
    fn formats_cq_entry_with_qth() {
        let log = vec![cq_entry("KD3BFP-9", "2026-07-27 20:45:39", Some("Pittsburgh, PA"))];
        let adif = format_adif(&log);
        assert!(adif.contains("<CALL:8>KD3BFP-9"));
        assert!(adif.contains("<QSO_DATE:8>20260727"));
        assert!(adif.contains("<TIME_ON:4>2045"));
        assert!(adif.contains("<MODE:6>PACKET"));
        assert!(adif.contains("<QTH:"));
        assert!(adif.contains("Pittsburgh, PA"));
        assert!(adif.contains("<EOR>"));
    }

    #[test]
    fn skips_non_cq_entries() {
        let log = vec![QsoLogEntry {
            callsign: "N0CALL-1".to_string(),
            port_id: "port-1".to_string(),
            started: "2026-07-27 20:45:39".to_string(),
            ended: Some("2026-07-27 20:50:00".to_string()),
            location: None,
            from_cq: false,
        }];
        let adif = format_adif(&log);
        assert!(!adif.contains("N0CALL-1"));
    }

    #[test]
    fn omits_qth_when_absent() {
        let log = vec![cq_entry("N0CALL-1", "2026-07-27 20:45:39", None)];
        let adif = format_adif(&log);
        assert!(adif.contains("<EOR>"));
        assert!(!adif.contains("<QTH:"));
    }
}
